on:
  push:
    branches:
      - "master"
      - "milestone-4"
  pull_request:
    branches:
      - "master"
      - "milestone-4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        run: flutter build appbundle