name: Auto Push

on:
  push:
    branches:
      - 'milestone-4'
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push changes
        uses: actions/github-push@v2
        with:
          github_token: ${{ secrets.TOKEN }}
