on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0" # Chọn phiên bản Flutter tương thích
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        run: flutter build appbundle
