name: Auto Push and Build APK

on:
  push:
    branches:
      - 'milestone-4'
      - 'master'

jobs:
  build_and_push:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "NguyenTran153"
          git config user.email "nguyentran.07052002ak@gmail.com"

      - name: Create and checkout master branch
        run: |
          git checkout -b master

      - name: Push changes
        run: |
          git push origin master milestone-4 --force
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build_apk:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ''

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk